# Generated by Django 3.2.10 on 2022-03-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0002_auto_20220318_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matricnumber',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Department',
            field=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('FoodTechnology', 'FoodTechnology'), ('Statistics', 'Statistics'), ('Business Administration', 'Business Administration')], default='ComputerScience', max_length=29),
        ),
    ]
