# Generated by Django 3.2.10 on 2022-03-31 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0004_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='Levels',
            field=models.CharField(choices=[('ND1 FT', 'ND1 FT'), ('ND1 PT', 'ND1 PT'), ('ND2 FT', 'ND2 FT'), ('ND2 PT', 'ND2 PT'), ('ND3 PT', 'ND3 PT'), ('HND1 FT', 'HND1 FT'), ('HND1 PT', 'HND1 PT'), ('HND2 FT', 'HND2 FT'), ('HND2 PT', 'HND2 PT'), ('HND3 PT', 'HND3 PT')], default='NDI', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{15,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matricnumber',
            field=models.CharField(max_length=15),
        ),
    ]
