# Generated by Django 3.2.10 on 2022-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0007_auto_20220331_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
