# Generated by Django 3.2.10 on 2022-04-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0013_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='Picture',
        ),
    ]
