# Generated by Django 3.2.10 on 2022-04-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0014_rename_image_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Picture',
            new_name='image',
        ),
    ]
