# Generated by Django 3.2.10 on 2022-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0016_auto_20220422_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
