# Generated by Django 3.2.10 on 2022-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0019_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default=2, upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
